# Generated by Django 4.0.1 on 2022-01-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviereview_movieid'),
        ('users', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.moviereview'),
        ),
    ]
