# Generated by Django 4.0.6 on 2022-07-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='albumId',
            field=models.CharField(max_length=50),
        ),
    ]
