# Generated by Django 4.1 on 2022-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_albumreview_albumid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='albumId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
