# Generated by Django 4.0.1 on 2022-01-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='movieId',
            field=models.IntegerField(),
        ),
    ]
