# Generated by Django 4.0.4 on 2022-06-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviereview_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
